In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session


# Corpus (C)
# Vocabluary(V)
#Document(d)

In [21]:
#one hot coding :SParse data set leads to overfitting
# Sparsity
# NO fixed size
# Out of vocalbuary
# No caputring of sementics meaning





In [12]:
# Bag of Words
# USes cosine for vector similarity
#order of words, context not matter
#matter on frequency of words
# words which are not in vocalbulary are taken care

df=pd.DataFrame({'text':["The brown fox jumps over the lazy dog.",
"A quick brown dog jumps over the lazy fox.",
"The lazy dog sleeps all day.",
"A lazy fox naps in the sun."],'output':[1,1,0,0]})
print("DF: ", df)


from sklearn.feature_extraction.text import  CountVectorizer
cv=CountVectorizer()
bag=cv.fit_transform(df['text'])



DF:                                           text  output
0      The brown fox jumps over the lazy dog.       1
1  A quick brown dog jumps over the lazy fox.       1
2                The lazy dog sleeps all day.       0
3                 A lazy fox naps in the sun.       0


In [15]:
print(cv.vocabulary_)
print(bag[0].toarray())
print(bag[1].toarray())

{'the': 13, 'brown': 1, 'fox': 4, 'jumps': 6, 'over': 9, 'lazy': 7, 'dog': 3, 'quick': 10, 'sleeps': 11, 'all': 0, 'day': 2, 'naps': 8, 'in': 5, 'sun': 12}
[[0 1 0 1 1 0 1 1 0 1 0 0 0 2]]
[[0 1 0 1 1 0 1 1 0 1 1 0 0 1]]


In [20]:
cv.transform(['fox eat the cow after killing dog, dog was  brown, fox was brown']).toarray()

array([[0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
#bag of words 
#disadvantage
#sparsity
#overfitting
#Ignoring out of vocabulary words causing loss of information
#bag of words does not consider ordering of words in sentence
    #"Example: Dog's name is Naomi"




In [24]:
# #n-grams(BAg of n-grams)
# # combination of words as vocabulary (continuous words)
# Ex: Bi-gram
#     The brown fox jumps over the lazy dog.
#     V:The brown 
#       brown fox 
#       fox jumps 
#       jumps over
#       over the 
#       the lazy
#       lazy dog.

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

In [31]:
bag=cv.fit_transform(df['text'])

In [32]:
cv.vocabulary_

{'the brown': 15,
 'brown fox': 2,
 'fox jumps': 5,
 'jumps over': 8,
 'over the': 12,
 'the lazy': 16,
 'lazy dog': 9,
 'quick brown': 13,
 'brown dog': 1,
 'dog jumps': 3,
 'lazy fox': 10,
 'dog sleeps': 4,
 'sleeps all': 14,
 'all day': 0,
 'fox naps': 6,
 'naps in': 11,
 'in the': 7,
 'the sun': 17}

In [34]:
print(bag[0].toarray())

[[0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0]]


In [35]:
#disadvantage
# V dimensionalit  increase Time increase
#no solution for new words out of vocabulary

In [38]:
#Tf-Idf
# Assign each words value(weightage)
# TF(Term frequency)
# IDF(inverse document frequency)


# d1="The brown fox jumps over the lazy dog.",
# d2="A quick brown dog jumps over the lazy fox.",
# d3="The lazy dog sleeps all day.",
# d4="A lazy fox naps in the sun."



# TF(t,d)=(no of occurence of term(t) in doccument (d))/(no of terms in document(d))
# Also between [0,1]
# Ex: TF(brown,d1)=(1/8)

#IDF(t)=Log[(No of documents(d) in corpus)/(no of document(d) with term (t) in them)]
#IDF(dog)=Log(4/3)


# Need log in idf Because it need to multiple with TF, if log not usede IDf , it will dominate since it will have large value 
# TF*IDF


# IMp: in skelarn actual 

# #IDF(t)=Log[(No of documents(d) in corpus)/(no of document(d) with term (t) in them)]+1
# to avoid ignoring words with idf '0'

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()


array([[0.        , 0.39219155, 0.        , 0.31751286, 0.31751286,
        0.        , 0.39219155, 0.25958757, 0.        , 0.39219155,
        0.        , 0.        , 0.        , 0.51917514],
       [0.        , 0.38360024, 0.        , 0.31055745, 0.31055745,
        0.        , 0.38360024, 0.25390107, 0.        , 0.38360024,
        0.48654826, 0.        , 0.        , 0.25390107],
       [0.50302425, 0.        , 0.50302425, 0.32107387, 0.        ,
        0.        , 0.        , 0.26249892, 0.        , 0.        ,
        0.        , 0.50302425, 0.        , 0.26249892],
       [0.        , 0.        , 0.        , 0.        , 0.32107387,
        0.50302425, 0.        , 0.26249892, 0.50302425, 0.        ,
        0.        , 0.        , 0.50302425, 0.26249892]])

In [43]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.51082562 1.91629073 1.22314355 1.22314355 1.91629073
 1.51082562 1.         1.91629073 1.51082562 1.91629073 1.91629073
 1.91629073 1.        ]
['all' 'brown' 'day' 'dog' 'fox' 'in' 'jumps' 'lazy' 'naps' 'over' 'quick'
 'sleeps' 'sun' 'the']


In [44]:
# #Advantage 
# Information retriveal(browser)
#disadvantage
#sparsity
#out of vocabulary 
#High dimensilty leads to overfitting